[workspace]
resolver = "2"
members = ["core", "wasm"]

[profile.release]
codegen-units = 1
incremental = true
lto = true
opt-level = "z"

[profile.dev.build-override]
opt-level = 3

[profile.release.build-override]
opt-level = 3
